# Dropshot's default configuration.
default: &DEFAULT
  server_ip: 0.0.0.0
  port: 3000
  db: db.sqlite
  ssl: true
  root: /

# Dropshot's test configuration.
test:
  server_ip: 127.0.0.1
  port: 6174
  db: test.sqlite
  ssl: false
  root: /test/

# Add your own configuration!
example:
  <<: *DEFAULT
  root: /example/
